#!/bin/bash

if [[ -f "vars.sh" ]]; then
    source "vars.sh"
else
    source "../vars.sh"
fi

GULP_CMD="gulp --no-change";
for param in "$@"
do
    if [ "$param" = "--production" ]; then
        GULP_CMD+=" --production";
    fi

    if [ "$param" = "--deploy" ]; then
        GULP_CMD+=" >/dev/null";
    fi
done

for MODULE in "${modules[@]}"
do
     echo -n "Building $MODULE ... "
     cd $MAIN/$MODULE
     rm -rf ./app/out
     find . -type f -name "*.html.ts" -delete
     eval $GULP_CMD
     if [ $? -ne 0 ] ; then
         echo "ERROR"
         echo "$?"
         exit 1;
     else
         echo "OK"
     fi
done
